---
- name: Ensure config dir
  become: true
  become_user: root
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items:
    - "{{ ssl_exporter_config_dir }}"
    - "{{ ssl_exporter_config_dir }}/sources"

- name: Copy ssl_exporter config file
  template:
    src: config.yml.j2
    dest: "{{ ssl_exporter_config_dir }}/config.yml"
    mode: 0644
    owner: root
    group: root

- name: Include docker-related tasks
  include_tasks: run_in_docker.yml
  when: ssl_exporter_run_in_docker

- name: Include standalone tasks
  include_tasks: run_standalone.yml
  when: not ssl_exporter_run_in_docker